name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: prepare-artifact-output
      run: |
        mkdir downloads
        cd downloads
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
    - name: cleanup
      run: cd ..
      
    - name: upload-artifact
      uses: actions/upload-artifact@v2
      with:
        path: downloads
      
      
      
